apiVersion: v1
kind: Pod                                            
metadata:
  name: sa-frontend
  labels:
    app: sa-frontend                                 
spec:                                               
  containers:
    - image: vladlenkiev/sentiment-analysis-frontend:0.2.2 # 4
      name: sa-frontend                              
      ports:
        - containerPort: 80                          
