version: '3.3'

services:
  sa-front:
    build: '../sa-frontend'
    ports:
      - 80:80
    networks:
      monitoring:
        aliases:
          - sa-front
  sa-web:
    build: '../sa-webapp'
    ports:
      - 8080:8080
    environment:
      - SA_LOGIC_API_URL=http://192.168.99.100:5000
    networks:
      monitoring:
        aliases:
          - sa-web
  sa-logic:
    build: '../sa-logic'
    #    image: prom/prometheus
    ports:
      - 5000:5000
#    volumes:
#      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
#      - ./prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - sa-logic
networks:
  monitoring:
