version: '3.3'
services:
  sa-front:
    build: '../sa-frontend'
    ports:
      - 80:80
    networks:
      my-network:
        aliases:
          - sa-front
  sa-web:
    build: '../sa-webapp'
    ports:
      - 8080:8080
    environment:
      - SA_LOGIC_API_URL=http://sa-logic:5000
    networks:
      my-network:
        aliases:
          - sa-web
  sa-logic:
    build: '../sa-logic'
    #    image: prom/prometheus
    ports:
      - 5000:5000
    networks:
      my-network:
        aliases:
          - sa-logic
networks:
  my-network:
    driver: bridge
    name: full-network
